2021-06-29 09:19:38,408 INFO     Starting Server with [Namespace(LOGFILE='./.log/PDF_KEYWORD_SERVER.log', production=False)]
2021-06-29 09:19:38,417 WARNING   * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-06-29 09:19:38,419 INFO      * Running on http://172.17.0.2:5001/ (Press CTRL+C to quit)
2021-06-29 09:19:50,925 INFO     127.0.0.1 - - [29/Jun/2021 09:19:50] "[32mGET / HTTP/1.1[0m" 302 -
2021-06-29 09:19:51,283 INFO     127.0.0.1 - - [29/Jun/2021 09:19:51] "GET /upload HTTP/1.1" 200 -
2021-06-29 09:20:04,894 INFO     127.0.0.1 - - [29/Jun/2021 09:20:04] "[32mPOST /upload HTTP/1.1[0m" 302 -
2021-06-29 09:20:05,062 ERROR    Exception on /info/pdf2Text_TEST_HELLOWORLD.pdf [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/workspaces/pdf2text/app/server.py", line 53, in info_file
    return render_template('file_upload_info.html', filename=name, text=text)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 150, in render_template
    ctx.app,
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/workspaces/pdf2text/app/templates/file_upload_info.html", line 9, in top-level template code
    <form id="form-text" action="http://localhost{{url_for('analyse_text')}}" method=post enctype=multipart/form-data>
  File "/usr/local/lib/python3.7/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.7/site-packages/flask/helpers.py", line 326, in url_for
    endpoint, values, method=method, force_external=external
  File "/usr/local/lib/python3.7/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'analyse_text'. Did you mean 'static' instead?
2021-06-29 09:20:05,084 INFO     127.0.0.1 - - [29/Jun/2021 09:20:05] "[35m[1mGET /info/pdf2Text_TEST_HELLOWORLD.pdf HTTP/1.1[0m" 500 -
2021-06-29 09:20:48,946 INFO     Starting Server with [Namespace(LOGFILE='./.log/PDF_KEYWORD_SERVER.log', production=False)]
2021-06-29 09:20:48,960 WARNING   * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-06-29 09:20:48,961 INFO      * Running on http://172.17.0.2:5001/ (Press CTRL+C to quit)
2021-06-29 09:20:51,664 INFO     127.0.0.1 - - [29/Jun/2021 09:20:51] "GET /info/pdf2Text_TEST_HELLOWORLD.pdf HTTP/1.1" 200 -
2021-06-29 09:20:53,616 INFO     127.0.0.1 - - [29/Jun/2021 09:20:53] "GET /uploads/pdf2Text_TEST_HELLOWORLD.pdf HTTP/1.1" 200 -
